# Logstash configuration for deployment on Kubernetes
persistence:
  enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    output {
      elasticsearch {
        hosts => "https://elasticsearch-master:9200"
        user => "elastic"
        password => "iliass"
        ssl => true
        cacert => "/usr/share/logstash/config/elasticsearch-master-certs/ca.crt"
        manage_template => false
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
      }
    }

service:
  type: ClusterIP
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: 5044
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080

secretMounts:
- name: "elasticsearch-master-certs"
  secretName: "elasticsearch-master-certs"
  path: "/usr/share/logstash/config/elasticsearch-master-certs"
